export const discoData = [
  {
    category: '2025',
    items: []
  },
  {
    category: '2024',
    items: []
  },
  {
    category: '2023',
    items: [
      { artist: "Elliot, oddbob, Itzel", album: "UNIVERS", credit: "Mix, Master" },
      { artist: "그리즐리", album: "와줘 Live", credit: "Mix" },
      { artist: "나히", album: "Rose", credit: "Mix" },
      { artist: "段奥娟 (Duan Aojuan)", album: "遗憾是暖的", credit: "Mix" },
      { artist: "성민지(미스트롯2)", album: "취향저격", credit: "Mix, Master" },
      { artist: "심가을", album: "니가 좋아하던 걸 기억해", credit: "Mix, Master" },
      { artist: "심가을", album: "좋은 이별이 어디 있나요", credit: "Mix, Master" },
      { artist: "유라(youra)", album: "꽤 많은 수의 촉수 돌기", credit: "All Track Record, Mix, Master (2024 한국대중음악상 수상)" },
      { artist: "음성녹음", album: "날카롭냐하는데", credit: "Record, Digital Edit" },
      { artist: "음성녹음", album: "우우우 나의 사랑", credit: "Record, Digital Edit" },
      { artist: "음성녹음", album: "Orange summer breeze", credit: "Record, Digital Edit" },
      { artist: "이재황", album: "HEY BABY", credit: "Master" },
      { artist: "플리", album: "낙엽터널", credit: "Digital Edit, Mix, Master" },
      { artist: "허회경", album: "김철수씨 이야기 Live", credit: "Location Record, Mix" },
      { artist: "허회경", album: "나와 내 이웃에게", credit: "Record, Digital Edit" },
      { artist: "허회경", album: "난 묻어요", credit: "Record, Digital Edit" },
      { artist: "허회경", album: "난 묻어요 Live", credit: "Location Record, Mix" },
      { artist: "허회경", album: "시시콜콜한 이야기", credit: "Record, Digital Edit" },
      { artist: "희서", album: "여름 뒷면 파랑 EP", credit: "All Track Record, Mix, Master" },
      { artist: "Aalia", album: "My Summer Night", credit: "Record, Mix" },
      { artist: "Itzel", album: "Dreaming Of The Days", credit: "Mix, Master" },
      { artist: "JT", album: "궁금해", credit: "Mix" },
      { artist: "Lemon City", album: "Hold me Kiss me Love me", credit: "Mix" },
      { artist: "Lemon City", album: "Nothing Without You", credit: "Mix" },
      { artist: "Lemon City", album: "What If I Told You", credit: "Mix" },
      { artist: "oddbob", album: "Shut Down", credit: "Mix, Master" },
      { artist: "Jackson Wang, Amber", album: "Super Ryce Bowl Concert", credit: "Mix" },
      { artist: "TFT Set 7", album: "쥬래ㅂ ㅐ 건의 땅 (Feat.노페갓)", credit: "Song Mix" }
    ]
  },
  {
    category: '2022',
    items: [
      { artist: "나히", album: "러브노트", credit: "Digital Edit, Mix" },
      { artist: "나히", album: "불면송", credit: "Digital Edit, Mix" },
      { artist: "성민지(미스트롯2)", album: "찌리리", credit: "Mix, Master" },
      { artist: "유라(youra)", album: "어떤 우울이 우리를 흔들겠어요", credit: "Record, Digital Edit" },
      { artist: "유라(youra)", album: "Jungle Bike", credit: "Record, Digital Edit" },
      { artist: "유라(youra), 만동", album: "이런 분위기는 기회다 (The Vibe is a Chance)", credit: "Vocal Record, Digital Edit" },
      { artist: "윤현상", album: "새벽 어귀", credit: "All Track Record, Digital Edit" },
      { artist: "최전설", album: "The Legend Begins - 전설의 시작", credit: "2, 3 Track(Title) Mix, Master" },
      { artist: "플리", album: "벚꽃이 피는 이 밤", credit: "Digital Edit, Mix, Master" },
      { artist: "허회경", album: "그렇게 살아가는 것", credit: "Live Mix" },
      { artist: "허회경", album: "사랑 속엔 언제나", credit: "Live Mix" },
      { artist: "허회경", album: "오 사랑아 Live", credit: "Record, Mix, Master" },
      { artist: "허회경", album: "정규 1집 Memoirs", credit: "1, 2, 3, 4, 7, 8, 9, 10 Track Record, Digital Edit" },
      { artist: "허회경", album: "Baby 나를", credit: "Record, Digital Edit" },
      { artist: "희서", album: "원", credit: "Record, Mix, Master" },
      { artist: "희서", album: "잠", credit: "Record, Mix, Master" },
      { artist: "Aalia", album: "숨멎", credit: "Live Mix" },
      { artist: "Aalia", album: "All I see is you", credit: "Record, Mix" },
      { artist: "Itzel", album: "ZOOM!", credit: "All Track Record, Mix, Master" },
      { artist: "jAne", album: "Trying to do What I can do", credit: "Mix, Master" },
      { artist: "oddbob", album: "Birthday", credit: "Record, Mix" },
      { artist: "Wonder", album: "I Wanna Christmas", credit: "Mix, Master" }
    ]
  },
  {
    category: '~2021',
    items: [
      { artist: "국카스텐", album: "적 같은 랜덤 (We Won't Cooperate) | 브롤스타즈 (Brawl Stars)", credit: "Location Record" },
      { artist: "김민지(슈퍼스타K 5)", album: "첫번째 상상", credit: "All Track Mix, Master" },
      { artist: "김민지(슈퍼스타K 5)", album: "하루하루", credit: "Mix, Master" },
      { artist: "노프라블럼", album: "봄꽃로맨스", credit: "Mix, Master" },
      { artist: "노프라블럼", album: "오늘 저녁 어때요", credit: "Mix, Master" },
      { artist: "롱디", album: "All night (Feat. 김도연 of 위키미키)", credit: "Record" },
      { artist: "롱디", album: "smile (feat. MK(ONF), Chawoo)", credit: "Record" },
      { artist: "박정현", album: "KBS World Radio OST One fine day", credit: "Mix" },
      { artist: "박정현", album: "the wonder", credit: "Track 6, 7 Vocal Record" },
      { artist: "성춘", album: "동네친구(Feat.김희서)", credit: "Mix, Master" },
      { artist: "성춘", album: "서울의 밤 (feat. 읆 Of 옆집언니)", credit: "Mix, Master" },
      { artist: "성춘", album: "어쩔 수 없나봐", credit: "Mix, Master" },
      { artist: "성춘", album: "SIGNATURE", credit: "All Track Mix, Master" },
      { artist: "신현희와 김루트", album: "The color of SEENROOT", credit: "All Track Record" },
      { artist: "유라(youra)", album: "하양 (Feat. 헤이즈)", credit: "Record, Digital Edit" },
      { artist: "유라(youra)", album: "GAUSSIAN", credit: "All Track Record, Digital Edit" },
      { artist: "유라(youra)", album: "my", credit: "Record" },
      { artist: "유라(youra)", album: "Night Running (Feat. 존박)", credit: "Record" },
      { artist: "유라(youra)", album: "Pacemaker", credit: "Record, Digital Edit" },
      { artist: "유라(youra)", album: "Rawww", credit: "Record, Digital Edit" },
      { artist: "크래커", album: "표정 (feat. 윤현상, 김이지)", credit: "Record" },
      { artist: "투유 프로젝트", album: "슈가맨2 Part.4 신현희와 김루트 - 경아의 하루", credit: "Record" },
      { artist: "허회경", album: "김철수씨 이야기", credit: "Record, Digital Edit" },
      { artist: "High Tension", album: "Chemistry", credit: "Master" },
      { artist: "High Tension", album: "Feel Me", credit: "Master" },
      { artist: "High Tension", album: "Memories", credit: "Mix, Master" },
      { artist: "High Tension", album: "Santiago (High Tension X Vinnatti)", credit: "Mix, Master" },
      { artist: "JT", album: "Color (Feat. 제기 of VX)", credit: "Mix, Master" },
      { artist: "monokim", album: "환상", credit: "Mix, Master" },
      { artist: "monokim", album: "Dorothy", credit: "Mix, Master" },
      { artist: "Northfacegawd", album: "복덕방", credit: "Mix, Master" },
      { artist: "Northfacegawd", album: "Northfacegawd (EP)", credit: "All Track Mix, Master" }
    ]
  }
];